const C = {
    TILE: 16,

    // World
    WORLD_W: 2400,
    WORLD_H: 900,
    LAVA_Y:  820,

    // Physics
    GRAVITY:       800,
    RUN_ACCEL:     2200,
    AIR_ACCEL:     900,
    GROUND_DRAG:   2800,
    AIR_DRAG:      80,
    SLIDE_DRAG:    55,
    MAX_RUN:       220,
    MAX_VEL_X:     1100,
    JUMP_VEL:      -320,
    AIR_JUMP_VEL:  -285,
    MAX_AIR_JUMPS: 2,
    DASH_VEL:      700,
    DASH_MS:       120,
    DASH_CD:       800,
    WALL_KICK_X:   480,
    WALL_KICK_Y:   -375,
    WALL_SLIDE_V:  50,
    HIT_STOP_MS:   90,

    // Camera
    ZOOM_CLOSE:      1.7,
    ZOOM_MID:        1.2,
    ZOOM_FAR:        0.82,
    ZOOM_NEAR_DIST:  90,
    ZOOM_FAR_DIST:   300,

    // Weapons
    WEAPONS: {
        sword: {
            id: 'sword',
            name: 'Sword',
            desc: 'Fast swings. Lunge on airborne attack.\nBest at sustained high speed.',
            atkDur:    180,
            atkCd:     500,
            radius:    22,
            dmgMin:    1,
            dmgMax:    38,
            swingCol:  0xddeeff,
            glowCol:   0x88aaff,
            lungeVel:  230,
        },
        hammer: {
            id: 'hammer',
            name: 'Sledgehammer',
            desc: 'One massive hit. Down+Z in air = ground slam.\nHigh risk, devastating reward.',
            atkDur:    500,
            atkCd:     1100,
            radius:    30,
            dmgMin:    8,
            dmgMax:    85,
            swingCol:  0xff8844,
            glowCol:   0xff4400,
            slamVel:   950,
            slamRadius: 65,
            slamBounce: -340,
        },
        axe: {
            id: 'axe',
            name: 'Axe',
            desc: 'Each hit charges your speed gauge.\nSnowballs into massive damage.',
            atkDur:    300,
            atkCd:     720,
            radius:    25,
            dmgMin:    3,
            dmgMax:    55,
            swingCol:  0xaaff55,
            glowCol:   0x66ff00,
            speedBonus: 15,
        },
        scythe: {
            id: 'scythe',
            name: 'Scythe',
            desc: 'Wide reaping arc. Kills reset cooldown.\nBurns 8 speed to swing — risk everything.',
            atkDur:    380,
            atkCd:     650,
            radius:    38,
            dmgMin:    5,
            dmgMax:    70,
            swingCol:  0xcc44ff,
            glowCol:   0x9900dd,
            gaugeCost: 8,
        },
    },
};
